---
galaxy_info:
  author: Yury Shelukhin
  description: Install and configure Vector
  company: Netology
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - vector
    - observability
    - clickhouse
dependencies: [] 
